# Generated by Django 3.2.3 on 2021-06-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=100)),
                ('youremail', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('massage', models.TextField()),
            ],
        ),
    ]
